version: 1
main:
  address: 0.0.0.0
  port: 5588
  env:
    MCP_ENABLED: "true"
    RUST_LOG: info
runners:
  local:
    address: 127.0.0.1
    count: 2
    port_range:
      start: 55880
      end: 55889
    env:
      RUST_LOG: info
